### ISSUE TITLE
Handle inference sets with some actuals

### ISSUE THREAD

**Issue by sinnec** [squaredev-io/whitebox#65]
In order to calculate performance metrics for a model, the actuals from the inference rows are required.
As of now, whitebox only handles the cases where an inference set has all the actuals or an inference set has no actuals. In case there's a set of inferences with only some actuals, the performance metrics pipeline won't work as expected.

Proposed solution:
Since actuals are optional, filter out those inference rows that don't have actuals and execute the performance metrics pipeline only for those rows that have actuals. In case there are no actuals at all, the pipeline will be skipped (that's already implemented).

**Comment by gcharis** [comment]
Create a subset for those that do have actuals, and drop the rest
