### ISSUE TITLE
Inserting timestamps and actuals of inferences through SDK

### ISSUE THREAD

**Issue by sinnec** [squaredev-io/whitebox#66]
The way SDK is designed at the moment, there are two issues concerning inferences:

Timestamps:
The user can insert a timestamp that will apply to the whole set of inferences but not to a specific row individually.

Actuals:
The user cannot insert actuals for the inferences. Even if they do by placing them in the processed dataframe, the SDK won't handle it and the 'actual' field will always be empty. Since there's no way for the user to update the actuals at a later time, the user will never get the performance metrics.

**Comment by gcharis** [comment]
The actuals can be fixed for the insert. Something similar must be done for the update in the future
