### ISSUE TITLE
Training model pipeline failing with KeyError

### ISSUE THREAD

**Issue by sinnec** [squaredev-io/whitebox#78]
The way the API and pipeline are designed right now:

- A user inserts their dataset rows and when saved to the database the training model pipeline is triggered.
- If everything is successful the trained model is saved in the user's filesystem.

Here there's a possibility that the pipeline will fail with a KeyError because the given target when creating a model doesn't exist in the training dataset (a user's fault). The thing is though that a trained model isn't produced and the dataset rows are saved in the database. The user can't delete them from the SDK or API and if they insert new and correct ones, it's going to cause a chaos with all the metrics calculations due to columns mismatches.

Suggested solutions:
1. Save the dataset rows in the database, train the model and if it fails (Raising a KeyError exception), delete the saved dataset rows from the database so the user can start fresh. OR
2. Before the dataset rows are saved in the database, check if the target exists in the dataset provided by the user.

**Comment by sinnec** [comment]
Checking for the appropriate column before the model training solves the KeyError, but in case of small training datasets (probably mistakenly inserted by the user) we can get a few other errors (like ValueError) that prevent the completion of the training and leave us with a similar problem to what we tackled in this issue.

<img width="997" alt="Screenshot 2023-01-03 at 13 21 30" src="https://user-images.githubusercontent.com/48223149/210348343-ac90237f-60d2-4e64-8449-6cd226dc7052.png">

<img width="997" alt="Screenshot 2023-01-03 at 13 22 01" src="https://user-images.githubusercontent.com/48223149/210348368-5cd7a7e5-6704-4cb3-aec3-717313c82fb2.png">

**Comment by stavrostheocharis** [comment]
@sinnec at the above example there is an one-row training dataset. I think that in such cases we should also capture it before even starting to save this data and raise an error. An one-row dataset is not considered a training dataset.
Maybe a solution could be to check the length of the given dataset and also to check if the given target column has more than one unique values.

**Comment by sinnec** [comment]
@stavrostheocharis  Training datasets above what length are acceptable, since the second ValueError (The one with ROC AUC) is occuring even for small datasets of 5 rows with different targets. Should it be something like `len(training_dataset) >= 100` or something?

**Comment by stavrostheocharis** [comment]
I think that more than 2 in could be ok. Maybe at your test dataset you have in all y values the same value (this would be a problem)
