### ISSUE TITLE
Check model monitor's status before creating alerts

### ISSUE THREAD

**Issue by sinnec** [squaredev-io/whitebox#80]
Currently the status of a monitor (active/inactive) isn't checked before running the checks for alert creation so even if a monitor is inactive it can create an alert.

Suggested Solutions:
- Check for the monitor's status before creating the alerts OR
-  Fetch only active monitors from the database in alerts pipeline.

**Comment by stavrostheocharis** [comment]
Fetch only active monitors from the database in alerts pipeline.
