### ISSUE TITLE
[Roadmap] Add regression models

### ISSUE THREAD

**Issue by momegas** [squaredev-io/whitebox#93]
# Description

Machine Learning Regression is a technique for investigating the relationship between independent variables or features and a dependent variable or outcome. It's used as a method for predictive modelling in machine learning, in which an algorithm is used to predict continuous outcomes.

Whitebox is currently producing metrics for classification models. We need to expand this to produce metrics for regression models as well.

## Metrics

Example of metrics: 

1. Mean Squared Error
2. Root Mean Squared Error
3. Mean Absolute Error

The outcome should be that the above metrics are stored in the database just like classification problems and then depending on the model the API needs to return the appropriate results.

**Comment by NickNtamp** [comment]
Also this ticket should include:

- Creation of a regression model for Lime explainability
- Documentation

**Comment by momegas** [comment]
Yeah yeah it includes all those 😄

**Comment by NickNtamp** [comment]
I am done in terms of code, the only leftover is the documentation. We agreed with @sinnec to start working in the same branch.

**Comment by momegas** [comment]
There is also the API and SDK 👀

**Comment by NickNtamp** [comment]
> There is also the API and SDK 

In the above comment I made totally clear that the work is not done here!
