### ISSUE TITLE
Metrics in docs

### ISSUE THREAD

**Issue by momegas** [squaredev-io/whitebox#94]

**Comment by NickNtamp** [comment]
Please review the docs under metrics and new glossary sections [here](https://github.com/squaredev-io/whitebox/pull/95).

There is a pending section regarding explainability. As it is a bit more tricky I would propose an indicative structure below and we could create a new task regarding this. Actually, not exactly structure but what I think that this chapter should include. 

1. Explainability
     1.1 Explain the confidence levels here. 
          _Level0_: Explain a model trained in the client's training data. 
          _Level1_: Explain a model trying to predict the predictions of clients model. (no extensive analysis as this is pending)
          _Level2_: Explain client's model. (no extensive analysis as this is pending)
     1.2 Level0 Confidence level.
     Talk a bit about the trained model (boost model)
     **QUESTIONS**
          Will we talk about the evaluation metrics of the model?
          Will the client have access to the evaluation metrics of the model?
          Will we mention fine-tuning as a pending enhancement here?
     Talk about explainability feature. (LIME)
     1.3 Level1 Confidence level. (Leave this as pending)
     1.4 Level2 Confidence level. (leave this as pending)

Please respond in an explicit manner to avoid any misunderstandings and back-and-forth. Thank you in advance. 
cc: @momegas , @stavrostheocharis
